name: Automatically Create PR and Add to Redmine on New Branches
concurrency: auto-pr-${{ github.ref }}
on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "dependabot/**"
      - "renovate/**"
      - "whitesource/**"
      - "testing"
      - "import"

permissions:
  contents: write
  pull-requests: write
  repository-projects: read
  actions: read
  statuses: read
  checks: read

jobs:
  pull-request:
    runs-on: ubuntu-latest
    outputs:
      pr_url: ${{ steps.open-pr.outputs.pr_url }}
      pr_num: ${{ steps.open-pr.outputs.pr_number }}
      pr_created: ${{ steps.open-pr.outputs.pr_created }}
    steps:
      - uses: actions/checkout@v7
      - id: open-pr
        run: |
          gh pr view && echo "pr_created=false" >> $GITHUB_OUTPUT || { 
            gh pr create -d -B "main" -l "auto-pr" -t "${{ github.ref_name }}" -b ""
            echo "pr_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
            echo "pr_url=$(gh pr view --json url -q .url || echo "")" >> $GITHUB_OUTPUT
            echo "pr_created=true" >> $GITHUB_OUTPUT
          }
        env:
          GH_TOKEN: ${{ github.token }}

  extractnum:
    needs: pull-request
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.extract.outputs.replaced }}
    steps:
      - id: extract
        uses: frabert/replace-string-action@v2.5
        with:
          pattern: "^(task|issue|bug)(\\d+)-.*$"
          flags: "i"
          string: "${{ github.ref_name }}"
          replace-with: "$2"

  link-to-redmine:
    needs: [extractnum, pull-request]
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' && needs.extractnum.outputs.issue != github.ref_name }}
    uses: pangaeatech/.github/.github/workflows/link-to-redmine.yml@main
    with:
      pr_num: ${{ needs.pull-request.outputs.pr_num }}
      pr_url: ${{ needs.pull-request.outputs.pr_url }}
      rm_issue: ${{ needs.extractnum.outputs.issue }}
      rm_url: "https://redmine.pangaeatech.com"
      rm_field_id: 11
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}

  add-to-redmine:
    needs: [extractnum, pull-request]
    if: ${{ needs.pull-request.outputs.pr_url && needs.pull-request.outputs.pr_created == 'true' && needs.extractnum.outputs.issue == github.ref_name }}
    uses: pangaeatech/.github/.github/workflows/add-to-redmine.yml@main
    with:
      pr_num: ${{ needs.pull-request.outputs.pr_num }}
      pr_url: ${{ needs.pull-request.outputs.pr_url }}
      pr_subject: ${{ github.ref_name }}
      rm_url: "https://redmine.pangaeatech.com"
      rm_project_id: "26cec-01"
      rm_field_id: 11
      rm_tracker_id: 29
      rm_version_id: 1038
    secrets:
      rm_key: ${{ secrets.REDMINE_API_KEY }}
